#!/bin/bash

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
KEYCLOAK_PORT=${KEYCLOAK_PORT:-8002}
KEYCLOAK_URL=${KEYCLOAK_URL:-http://localhost:$KEYCLOAK_PORT}
KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN:-admin}
KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-admin123}
KEYCLOAK_CONTAINER_NAME=${KEYCLOAK_CONTAINER_NAME:-keycloak}
KEYCLOAK_VOLUME_NAME=${KEYCLOAK_VOLUME_NAME:-keycloak_data}
KEYCLOAK_RUN_CONTAINER=${KEYCLOAK_RUN_CONTAINER:-true}
KEYCLOAK_REALM=${KEYCLOAK_REALM:-authentication-demo}
CONTAINER_RUNTIME=${CONTAINER_RUNTIME:-docker}

# Token Exchange V2 configuration (client secret set after setup)
export OIDC_ISSUER_URL=${OIDC_ISSUER_URL:-"$KEYCLOAK_URL/realms/$KEYCLOAK_REALM"}
export OIDC_CLIENT_ID=${OIDC_CLIENT_ID:-"authentication-demo"}
